version: "3"
services:
  database:
    image: postgres
    container_name: mvp-acft-db
    restart: unless-stopped
    # Load all env vars from .env into the container's environment
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - mvp-acft_network
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
  server:
    image: mvp-acft/server
    container_name: mvp-acft-api
    restart: unless-stopped
    build: ./server
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      NODE_ENV: development
      PORT: 80
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - mvp-acft_network
    volumes:
      # Allows live reload inside a docker container
      - ./server/src:/code/src
    command: npm start
  client:
    image: mvp-acft/client
    container_name: mvp-acft-app
    restart: unless-stopped
    build: ./client
    environment:
      API_URL: http://mvp-acft-api
      PORT: ${SERVER_PORT}
    depends_on:
      - server
    ports:
      - ${CLIENT_PORT}:80
    networks:
      - mvp-acft_network
    volumes:
      # Allows live reload inside a docker container
      - ./client/src:/code/src
networks:
  mvp-acft_network:
volumes:
  pg-data:
