### All Persons
GET http://localhost:3000/api/fitness/person

### Person by ID
GET http://localhost:3000/api/fitness/person?id=10

### Person by name
GET http://localhost:3000/api/fitness/person?name=Bob

### All tests
GET http://localhost:3000/api/fitness/test

### Test by ID
GET http://localhost:3000/api/fitness/test?testID=3

### All tests for person by ID
GET http://localhost:3000/api/fitness/test?personID=2

### All tests for person by name
GET http://localhost:3000/api/fitness/test?name=Susan

### Create person
POST http://localhost:3000/api/fitness/person
Content-Type: application/json

{
    "name": "Suzan",
    "gender": "F",
    "age": 21
}

### Update person
PUT http://localhost:3000/api/fitness/person/6
Content-Type: application/json

{
    "name": "Anna",
    "gender": "F",
    "age": 37
}

### Update person
PATCH http://localhost:3000/api/fitness/person/2
Content-Type: application/json

{
    "name": "Margarett"
}

### Delete person by id
DELETE http://localhost:3000/api/fitness/person/9

### Create test
POST http://localhost:3000/api/fitness/test
Content-Type: application/json

{
    "pushup_score": 65,
    "situp_score": 56,
    "date": "2023-04-10 09:45:00",
    "person_id": 13
}

### Update test by id
PUT http://localhost:3000/api/fitness/test/6
Content-Type: application/json

{
    "pushup_score": 65,
    "situp_score": 56,
    "date": "2023-04-10 09:45:00",
    "person_id": 13
}

### Delete test by id
DELETE http://localhost:3000/api/fitness/test/9