###
GET http://localhost:3000

###
GET http://localhost:3001/api/people?something=Bob&second=something

###
GET http://localhost:3001/api/people/1

###
GET http://localhost:3000/api/fitness/all-persons

###
GET http://localhost:3000/api/fitness/all-tests

###
GET http://localhost:3000/api/fitness/person-by-name/Bob

###
GET http://localhost:3000/api/fitness/person-by-id/7

### All tests under a person by their id
GET http://localhost:3000/api/fitness/person-tests/10

###
POST http://localhost:3000/api/fitness/create-person
Content-Type: application/json

{
    "name": "Anna",
    "gender": "F",
    "age": 21
}

###
PUT http://localhost:3000/api/fitness/update-person/6
Content-Type: application/json

{
    "name": "Anna",
    "gender": "F",
    "age": 22
}

###
DELETE http://localhost:3000/api/fitness/delete-person/8

###
POST http://localhost:3000/api/fitness/create-test/
Content-Type: application/json

{
    "pushup_score": 65,
    "situp_score": 56,
    "date": "2023-04-10 09:45:00",
    "person_id": 6
}

###
PUT http://localhost:3000/api/fitness/update-test/6
Content-Type: application/json

{
    "pushup_score": "Anna",
    "situp_score": "F",
    "date": 22,
    "person_id": 3
}