### All Persons
GET http://localhost:3000/api/fitness/person

### Person by ID
GET http://localhost:3000/api/fitness/person?id=20

### Person by name
GET http://localhost:3000/api/fitness/person?name=Jeff

### All tests
GET http://localhost:3000/api/fitness/test

### Test by ID
GET http://localhost:3000/api/fitness/test?testID=3

### All tests for person by ID
GET http://localhost:3000/api/fitness/test?personID=2

### All tests for person by name
GET http://localhost:3000/api/fitness/test?name=Kyle

### Create person
POST http://localhost:3000/api/fitness/person/create
Content-Type: application/json

{
    "name": "Anna",
    "gender": "F",
    "age": 21
}

### Update person
PUT http://localhost:3000/api/fitness/person/update/6
Content-Type: application/json

{
    "name": "Anna",
    "gender": "F",
    "age": 37
}

### Update person
PATCH http://localhost:3000/api/fitness/person/update/6
Content-Type: application/json

{
    "name": "Lissa"
}

### Delete person by id
DELETE http://localhost:3000/api/fitness/person/delete/11

### Create test
POST http://localhost:3000/api/fitness/test/create
Content-Type: application/json

{
    "pushup_score": 65,
    "situp_score": 56,
    "date": "2023-04-10 09:45:00",
    "person_id": 13
}

### Update test by id
PUT http://localhost:3000/api/fitness/test/update/6
Content-Type: application/json

{
    "pushup_score": 65,
    "situp_score": 56,
    "date": "2023-04-10 09:45:00",
    "person_id": 13
}