### All Persons ordered by name
GET http://localhost:3000/api/acft/person

### Person by ID
GET http://localhost:3000/api/acft/person?id=3



### All tests
GET http://localhost:3000/api/acft/test

### ACFT by test ID
GET http://localhost:3000/api/acft/test?id=4

### All tests for a person by person ID, ordered by test date descending
GET http://localhost:3000/api/acft/test?personID=7

### Latest tests for person by ID
GET http://localhost:3000/api/acft/test?personID=3&latest=true



### Create person
POST http://localhost:3000/api/acft/person
Content-Type: application/json

{
    "name": "Tim",
    "gender": "M",
    "age": 30
}

### Update person by ID (all fields)
PUT http://localhost:3000/api/acft/person/4
Content-Type: application/json

{
    "name": "Tom",
    "gender": "M",
    "age": 32
}

### Update person by ID (misc fields)
PATCH http://localhost:3000/api/acft/person/4
Content-Type: application/json

{
    "name": "Tim"
}

### Delete person by id
DELETE http://localhost:3000/api/acft/person/4



### Create test
POST http://localhost:3000/api/acft/test
Content-Type: application/json

{
    "age": 32,
    "mdl": 220,
    "spt": 7.7,
    "hrp": 65,
    "sdc": "00:02:15",
    "plk": "00:02:45",
    "run": "00:18:45",
    "walk": null,
    "bike": null,
    "swim": null,
    "kmrow": null,
    "date": "2023-04-10",
    "person_id": 12
}

### Update test by id (all fields)
PUT http://localhost:3000/api/acft/test/6
Content-Type: application/json

{
    "age": 32,
    "mdl": 220,
    "spt": 7.7,
    "hrp": 65,
    "sdc": "00:02:15",
    "plk": "00:02:45",
    "run": "00:18:45",
    "walk": null,
    "bike": null,
    "swim": null,
    "kmrow": null,
    "date": "2023-04-10",
    "person_id": 4
}

### Update test by ID (misc fields)
PATCH http://localhost:3000/api/acft/test/14
Content-Type: application/json

{
    "sdc": "00:02:15",
    "plk": "00:02:45",
    "run": "00:18:45"
}

### Delete test by ID
DELETE http://localhost:3000/api/acft/test/11